extern const GeoLayout mingleDoor_001_switch_opt1[];
extern const GeoLayout mingleDoor_001_switch_opt2[];
extern const GeoLayout mingleDoor_001_switch_opt3[];
extern const GeoLayout mingleDoor_001_switch_opt4[];
extern const GeoLayout mingleDoor_001_switch_opt5[];
extern const GeoLayout mingleDoor_001_switch_opt6[];
extern const GeoLayout mingleDoor_001_switch_opt7[];
extern const GeoLayout mingleDoor_geo[];
extern u8 mingleDoor_PORTE_ia16[];
extern Vtx mingleDoor_000_displaylist_001_mesh_layer_4_vtx_0[22];
extern Gfx mingleDoor_000_displaylist_001_mesh_layer_4_tri_0[];
extern Gfx mat_mingleDoor_porte0[];
extern Gfx mat_revert_mingleDoor_porte0[];
extern Gfx mat_mingleDoor_porte1[];
extern Gfx mat_revert_mingleDoor_porte1[];
extern Gfx mat_mingleDoor_porte2[];
extern Gfx mat_revert_mingleDoor_porte2[];
extern Gfx mat_mingleDoor_porte3[];
extern Gfx mat_revert_mingleDoor_porte3[];
extern Gfx mat_mingleDoor_porte4[];
extern Gfx mat_revert_mingleDoor_porte4[];
extern Gfx mat_mingleDoor_porte5[];
extern Gfx mat_revert_mingleDoor_porte5[];
extern Gfx mat_mingleDoor_porte6[];
extern Gfx mat_revert_mingleDoor_porte6[];
extern Gfx mat_mingleDoor_porte7[];
extern Gfx mat_revert_mingleDoor_porte7[];
extern Gfx mingleDoor_000_displaylist_001_mesh_layer_4[];
extern Gfx mingleDoor_000_displaylist_001_mesh_layer_4_mat_override_porte1_0[];
extern Gfx mingleDoor_000_displaylist_001_mesh_layer_4_mat_override_porte2_1[];
extern Gfx mingleDoor_000_displaylist_001_mesh_layer_4_mat_override_porte3_2[];
extern Gfx mingleDoor_000_displaylist_001_mesh_layer_4_mat_override_porte4_3[];
extern Gfx mingleDoor_000_displaylist_001_mesh_layer_4_mat_override_porte5_4[];
extern Gfx mingleDoor_000_displaylist_001_mesh_layer_4_mat_override_porte6_5[];
extern Gfx mingleDoor_000_displaylist_001_mesh_layer_4_mat_override_porte7_6[];
